CREATE TABLE pessoa (
	codigo BIGINT(20) AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	ativo VARCHAR(10) NOT NULL,
	logradouro VARCHAR(50) NOT NULL,
	numero VARCHAR(10) NOT NULL,
	complemento VARCHAR(50) NOT NULL,
	bairro VARCHAR(30) NOT NULL,
	cep VARCHAR(15) NOT NULL,
	cidade VARCHAR(30) NOT NULL,
	estado VARCHAR(30) NOT NULL,
	PRIMARY KEY(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
